//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_NT_Taller_Meacanico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autopart
    {
        public Autopart()
        {
            this.Order_Autopart = new HashSet<Order_Autopart>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public decimal price { get; set; }
    
        public virtual ICollection<Order_Autopart> Order_Autopart { get; set; }
    }
}
