//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_NT_Taller_Meacanico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Addresses = new HashSet<Address>();
            this.Orders = new HashSet<Order>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int personal_id { get; set; }
        public Nullable<int> telephone { get; set; }
        public int address_id { get; set; }
        public int workshop_id { get; set; }
    
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual Mechanical_Workshop Mechanical_Workshop { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
