//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_NT_Taller_Meacanico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mechanical_Workshop
    {
        public Mechanical_Workshop()
        {
            this.Clients = new HashSet<Client>();
            this.Employees = new HashSet<Employee>();
            this.Orders = new HashSet<Order>();
        }
    
        public string name { get; set; }
        public int id { get; set; }
    
        public virtual ICollection<Client> Clients { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
