//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_NT_Taller_Meacanico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mechanical_Workshop
    {
        public string name { get; set; }
    }
}
